name: Trigger auto deployment for ca-cicd-test-20241103

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-cicd-test-20241103-AutoDeployTrigger-354d49b6-d34c-44e6-b3a7-9fbd9724e43d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CACICDTEST20241103_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CACICDTEST20241103_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CACICDTEST20241103_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: crcicdtest20241103.azurecr.io
          registryUsername: ${{ secrets.CACICDTEST20241103_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CACICDTEST20241103_REGISTRY_PASSWORD }}
          containerAppName: ca-cicd-test-20241103
          resourceGroup: rg-container-test-001
          imageToBuild: crcicdtest20241103.azurecr.io/ca-cicd-test-20241103:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


